### ISSUE TITLE
No data entries

### ISSUE THREAD

**Issue by muddeatr** [DNNCommunity/Dnn.SiteLog#8]
I have installed this 8.0 version of SiteLog but it does not work at all. There is nowhere to change the settings. The database has no entries in it. The module says It's been disabled by the host. There are directions for "Enabling the Site LogEnabling" but unfortunately the following is not very helpful. "The Site Log is disabled by default and must be enabled and configured by a Super User before it can be used to generate reports."

**Comment by muddeatr** [comment]
I inserted a record in the PortalSettings table: SettingName = 'SiteLogHistory', SettingValue = 90
This made the extension start to work, but the UserID was not filled out. I then followed the steps in the previous comment the ID.

**Comment by valadas** [comment]
Please watch for a 8.0.1 release in the next following days, I am merging 2 pull requests that will resolve most of the duplicate issues reported in this repository, basically the module was extracted but had no settings until now because they where removed from site settings. The settings will now be in the module settings.
